api:
  replicaCount: 1
  image:
    repository: docker.io/abamboi/economic-api:main-0853e11-20221009
    pullPolicy: Always
    imagePullSecrets:
      name: dockerhub-login
      create: false
      username: ''
      password: ''
      registryUrl: https://index.docker.io/v1/
  nameOverride: ''
  fullnameOverride: ''
  service:
    type: ClusterIP
    port: 8080
    targetPort: 5001
    name: api
  resources:
    limits:
      cpu: 250m
      memory: 1050Mi
    requests:
      cpu: 250m
      memory: 10508Mi
