
{{ if and .Values.api.image.imagePullSecrets.name .Values.api.image.imagePullSecrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.image.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}