apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }}
  labels:
{{- include "app.labels" $ | nindent 6 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- include "app.selectorLabels" $ | nindent 6 }}